### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by you-jin-choi** [you-jin-choi/prepare-todoList#1]
### 만들고자 하는 기능 
- Todo 생성
- Todo 조회
- Todo 삭제

### 해당 기능 구현을 위해 할 일
1. [ ] API 계층 구현 (Controller, Dto)
2. [ ] Business 계층 구현 (Service, Entity, Mapper)
3. [ ] Data Access 계층 구현 (Repository)

### 예상 작업시간
10hrs
